# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centralizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x65ntralizer.proto\"3\n\x0fRegisterRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"$\n\x10RegisterResponse\x12\x10\n\x08num_keys\x18\x01 \x01(\x05\"\x1c\n\rMapKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"$\n\x0eMapKeyResponse\x12\x12\n\nidentifier\x18\x01 \x01(\t\"\x12\n\x10TerminateRequest2\x9c\x01\n\x0b\x43\x65ntralizer\x12/\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12)\n\x06MapKey\x12\x0e.MapKeyRequest\x1a\x0f.MapKeyResponse\x12\x31\n\tTerminate\x12\x11.TerminateRequest\x1a\x11.RegisterResponseb\x06proto3')



_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
_MAPKEYREQUEST = DESCRIPTOR.message_types_by_name['MapKeyRequest']
_MAPKEYRESPONSE = DESCRIPTOR.message_types_by_name['MapKeyResponse']
_TERMINATEREQUEST = DESCRIPTOR.message_types_by_name['TerminateRequest']
RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'centralizer_pb2'
  # @@protoc_insertion_point(class_scope:RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'centralizer_pb2'
  # @@protoc_insertion_point(class_scope:RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

MapKeyRequest = _reflection.GeneratedProtocolMessageType('MapKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPKEYREQUEST,
  '__module__' : 'centralizer_pb2'
  # @@protoc_insertion_point(class_scope:MapKeyRequest)
  })
_sym_db.RegisterMessage(MapKeyRequest)

MapKeyResponse = _reflection.GeneratedProtocolMessageType('MapKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAPKEYRESPONSE,
  '__module__' : 'centralizer_pb2'
  # @@protoc_insertion_point(class_scope:MapKeyResponse)
  })
_sym_db.RegisterMessage(MapKeyResponse)

TerminateRequest = _reflection.GeneratedProtocolMessageType('TerminateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATEREQUEST,
  '__module__' : 'centralizer_pb2'
  # @@protoc_insertion_point(class_scope:TerminateRequest)
  })
_sym_db.RegisterMessage(TerminateRequest)

_CENTRALIZER = DESCRIPTOR.services_by_name['Centralizer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=21
  _REGISTERREQUEST._serialized_end=72
  _REGISTERRESPONSE._serialized_start=74
  _REGISTERRESPONSE._serialized_end=110
  _MAPKEYREQUEST._serialized_start=112
  _MAPKEYREQUEST._serialized_end=140
  _MAPKEYRESPONSE._serialized_start=142
  _MAPKEYRESPONSE._serialized_end=178
  _TERMINATEREQUEST._serialized_start=180
  _TERMINATEREQUEST._serialized_end=198
  _CENTRALIZER._serialized_start=201
  _CENTRALIZER._serialized_end=357
# @@protoc_insertion_point(module_scope)
