# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\"-\n\x0fKeyValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"/\n\x11\x41\x63tivationRequest\x12\x1a\n\x12service_identifier\x18\x01 \x01(\t\")\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x10TerminateRequest2\xaf\x01\n\rKeyValueStore\x12%\n\x06Insert\x12\x10.KeyValueRequest\x1a\t.Response\x12!\n\x07\x43onsult\x12\x0b.KeyRequest\x1a\t.Response\x12)\n\x08\x41\x63tivate\x12\x12.ActivationRequest\x1a\t.Response\x12)\n\tTerminate\x12\x11.TerminateRequest\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEYVALUEREQUEST']._serialized_start=17
  _globals['_KEYVALUEREQUEST']._serialized_end=62
  _globals['_KEYREQUEST']._serialized_start=64
  _globals['_KEYREQUEST']._serialized_end=89
  _globals['_ACTIVATIONREQUEST']._serialized_start=91
  _globals['_ACTIVATIONREQUEST']._serialized_end=138
  _globals['_RESPONSE']._serialized_start=140
  _globals['_RESPONSE']._serialized_end=181
  _globals['_TERMINATEREQUEST']._serialized_start=183
  _globals['_TERMINATEREQUEST']._serialized_end=201
  _globals['_KEYVALUESTORE']._serialized_start=204
  _globals['_KEYVALUESTORE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
